language: node_js
sudo: false
node_js:
  - 12
  - 11
  - 10

addons:
  sonarcloud:
    organization: "enib-internships"
    token:
      secure: "2b0f2c712104117023c26c2be56229f9dadb3918" # encrypted value of your token

install:
  - npm install

jobs:
  include:
    - stage: "Lints"
      name: "Lint webapp"
      script: 'npm run lint:app'
    - script: 'npm run lint:services'
      name: "Lint services"

    - stage: "Tests"
      name: "Unit Tests webapp"
      script: npm run test:unit:app
    - script: npm run test:unit:services
      name: "Unit Tests services"

    - stage: "Sonar scan"
      name: "Sonar scan"
      script: sonar-scanner
