language: node_js
sudo: false
node_js:
  - 12
  - 11
  - 10

addons:
  sonarcloud:
    organization: "enib-internships"
    token:
      secure: "2b0f2c712104117023c26c2be56229f9dadb3918" # encrypted value of your token

install:
  - npm install
script:
  - npm run lint
  - sonar-scanner
